from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as ec
from time import sleep
from pathlib import Path
from datetime import date
import openpyxl
import pytest
from selenium.webdriver.common.keys import Keys

class Test_Pegasus:
    def setup_method(self):
        self.driver = webdriver.Chrome(ChromeDriverManager().install())
        self.driver.get("https://www.flypgs.com")
        self.driver.maximize_window()
        self.folderPath = str(date.today())
        Path(self.folderPath).mkdir(exist_ok=True)
        btnAccept = self.driver.find_element(By.XPATH,"//*[@id='nxm2CookieSubmitButton']")
        btnAccept.click()

    def teardown_method(self):
        self.driver.quit()

    def wait(self,locator):
        WebDriverWait(self.driver,5).until(ec.visibility_of_element_located((locator)))

    def scrollTo(self,value):
        self.driver.execute_script(f"window.scrollTo(0,{value})")

    def getPnr():
        excelFile = openpyxl.load_workbook("data/invalid_login.xlsx")
        selectedSheet = excelFile["Sheet1"]
        totalRows = selectedSheet.max_row
        data = []
        for i in range(2,totalRows+1):
            txtCode = selectedSheet.cell(i,1).value
            txtSurname = selectedSheet.cell(i,2).value
            tupleData = (txtCode,txtSurname)
            data.append(tupleData)
        return data
    def action(self,btn):
        action = ActionChains(self.driver)
        action.move_to_element(btn).perform()

    #Kampanyalar Buton Testi
    def test_mainNovListOffer(self):
        self.wait((By.XPATH,"/html/body/header/nav/ul"))
        btnOffer = self.driver.find_element(By.XPATH,"/html/body/header/nav/ul/li[1]")
        btnOffer.click()
        self.scrollTo(200)
        sleep(1)
        self.driver.save_screenshot(f"{self.folderPath}/offer.png")
        btnDetail = self.driver.find_element(By.XPATH,"/html/body/section[3]/div/div[2]/div[2]/div[2]/a")
        btnDetail.click()
        self.scrollTo(200)
        sleep(1)
        self.scrollTo(800)
        sleep(1)
        self.driver.save_screenshot(f"{self.folderPath}/offerDetail-1.png")
        self.driver.back()
        self.scrollTo(500)
        sleep(1)
        self.driver.save_screenshot(f"{self.folderPath}/offerDetail-2.png")
        btnMorePlay = self.driver.find_element(By.XPATH,"/html/body/section[3]/div/div[3]/div[2]/div[2]/a")
        btnMorePlay.click()
        self.scrollTo(200)
        self.driver.save_screenshot(f"{self.folderPath}/offerDetail-3.png")
        sleep(1)
        self.scrollTo(900)
        self.driver.save_screenshot(f"{self.folderPath}/offerDetail-4.png")
        sleep(1)
        self.driver.back()
        self.scrollTo(0)
        btnAllDetail = self.driver.find_element(By.XPATH,"/html/body/section[3]/div/div[1]/div/a")
        btnAllDetail.click()
        self.scrollTo(200)
        sleep(2)
        self.driver.save_screenshot(f"{self.folderPath}/offerAll-5.png")
        self.scrollTo(400)
        sleep(1)
        self.driver.save_screenshot(f"{self.folderPath}/offerAll-6.png")
        self.scrollTo(1500)
        btnMoreAll = self.driver.find_element(By.ID,"nxm-pastCampaigns")
        btnMoreAll.click()
        self.scrollTo(1900)
        sleep(2)
        self.driver.save_screenshot(f"{self.folderPath}/offerAll-7.png")

    #Bilet İşlemleri Testi
    @pytest.mark.parametrize("txtCode,txtSurname",getPnr())
    def test_mainNovListTicket(self,txtCode,txtSurname):
        btnTicketTransactions = self.driver.find_element(By.XPATH,"/html/body/header/nav/ul/li[2]")
        btnTicketTransactions.click()
        self.scrollTo(100)
        txtCod = self.driver.find_element(By.XPATH,"(//input[@type='text'])[2]")
        txtCod.send_keys(txtCode)
        txtSurnam = self.driver.find_element(By.XPATH,"(//input[@type='text'])[3]")
        txtSurnam.send_keys(txtSurname)
        btnContinue = self.driver.find_element(By.XPATH,"/html/body/section[3]/div/article/form/div[3]/div/div[1]/button")
        sleep(2)
        self.driver.save_screenshot(f"{self.folderPath}/ticket-8.png")
        btnContinue.click()
        self.driver.save_screenshot(f"{self.folderPath}/NotNullPNR.png")
        if (txtCode == " ") or (txtSurname == " "):
            self.wait((By.XPATH,"//form/div/div/ul/li"))
            txtError = self.driver.find_element(By.XPATH,"//form/div/div/ul/li")
            assert txtError.text == "6 haneli PNR numaranızı veya 13 haneli E-Bilet numaranızı giriniz."
            sleep(2)
            self.driver.save_screenshot(f"{self.folderPath}/NullPNR.png")
        self.scrollTo(1000)
        sleep(2)
        self.driver.save_screenshot(f"{self.folderPath}/FindTicket.png")
        btnCity = self.driver.find_element(By.XPATH,f"//div[2]/a[9]")
        self.action(btnCity)
        btnCity.click()
        btnDate = self.driver.find_element(By.XPATH,"//*[@id='fligth-searh']/div[3]/div[2]")
        btnDate.click()
        self.wait((By.XPATH,"//*[@id='search-flight-datepicker-arrival']/div/div[1]/table/tbody/tr[4]/td[4]/a"))
        btnChooseDate = self.driver.find_element(By.XPATH,"//*[@id='search-flight-datepicker-arrival']/div/div[1]/table/tbody/tr[4]/td[4]/a")
        btnChooseDate.click()
        btnMoreDay = self.driver.find_element(By.XPATH,"//*[@id='fligth-searh']/label/span")
        btnMoreDay.click()
        btnCheapTicket = self.driver.find_element(By.XPATH,"//*[@id='fligth-searh']/div[3]/div[4]")
        self.driver.save_screenshot(f"{self.folderPath}/PragTicket.png")
        btnCheapTicket.click()
        self.scrollTo(500)
        sleep(2)
        self.wait((By.XPATH,"//*[@id='boarding-card-body']/div/div[3]/div[1]/div[1]/div[2]/div[3]/div[1]/div/div/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[5]/td[1]"))
        btnChooseTicketGo = self.driver.find_element(By.XPATH,"//*[@id='boarding-card-body']/div/div[3]/div[1]/div[1]/div[2]/div[3]/div[1]/div/div/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[5]/td[1]")
        btnChooseTicketGo.click()
        self.driver.save_screenshot(f"{self.folderPath}/TickerForGo.png")
        self.scrollTo(300)
        sleep(2)
        self.wait((By.XPATH,"//div[2]/div[2]/div/div/div/div/div[4]/div/div/div[2]"))
        btnOtherDate = self.driver.find_element(By.XPATH,"//div[2]/div[2]/div/div/div/div/div[4]/div/div/div[2]")
        btnOtherDate.click()
        self.driver.save_screenshot(f"{self.folderPath}/OtherDate.png")
        self.scrollTo(500)
        sleep(2)
        self.wait((By.XPATH,"//*[@id='boarding-card-body']/div/div[3]/div[1]/div[2]/div[2]/div[3]/div[1]/div/div/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[4]/td[5]"))
        btnChooseTicketBack = self.driver.find_element(By.XPATH,"//*[@id='boarding-card-body']/div/div[3]/div[1]/div[2]/div[2]/div[3]/div[1]/div/div/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[4]/td[5]")
        btnChooseTicketBack.click()
        sleep(2)
        self.driver.save_screenshot(f"{self.folderPath}/TicketForBak.png")
        self.scrollTo(1000)
        self.wait((By.XPATH,"//*[@id='boarding-card-body']/div/div[3]/div[3]/div/div[2]/button"))
        btnChooseContinue = self.driver.find_element(By.XPATH,"//*[@id='boarding-card-body']/div/div[3]/div[3]/div/div[2]/button")
        btnChooseContinue.click()
        sleep(1)
        self.scrollTo(500)
        self.wait((By.XPATH,"//*[@id='boarding-card-body']/div/div[3]/div[2]/button"))
        btnTryAgain = self.driver.find_element(By.XPATH,"//*[@id='boarding-card-body']/div/div[3]/div[2]/button")
        btnTryAgain.click()
        sleep(1)
        self.driver.save_screenshot(f"{self.folderPath}/ChooseContinue.png")
    #Hizmetlerimiz
    def test_service(self):
        for i in range(1,24):
            btnAgain = self.driver.find_element(By.ID,"nexum_services_menu_label")
            self.action(btnAgain)
            sleep(2)
            btnBenefitInf = self.driver.find_element(By.ID,"use_information_main_category")
            self.action(btnBenefitInf)
            self.wait((By.ID,f"use_information_{i}_label"))
            btnService1 = self.driver.find_element(By.ID,f"use_information_{i}_label")
            self.action(btnService1)
            sleep(1)
            btnService1.click()
            self.scrollTo(250)
            sleep(1)
            self.driver.save_screenshot(f"{self.folderPath}/Information-{i}.png")
            if i == 9:
                self.wait((By.ID,"onetrust-close-btn-container"))
                btnClose = self.driver.find_element(By.ID,"onetrust-close-btn-container")
                btnClose.click()
                self.wait((By.ID,"menu_icon_AHL_btn"))
                self.driver.save_screenshot(f"{self.folderPath}/Information-{i}.png")
                sleep(5)
                self.driver.back()
    #BOL-BOL
    def test_moreMore(self):
        btnMoremore = self.driver.find_element(By.ID,"nexum_bolbol_menu_label")
        btnMoremore.click()
        self.wait((By.XPATH,"//div[3]/div/i"))
        self.driver.save_screenshot(f"{self.folderPath}/CloseBtn.png")
        btnClose = self.driver.find_element(By.XPATH,"//div[3]/div/i")
        btnClose.click()
        for i in range(1,5):
            btnMores = self.driver.find_element(By.XPATH,f"//ul/div/div/div[{i}]/a")
            btnMores.click()
            self.scrollTo(100)
            sleep(1)
            self.driver.save_screenshot(f"{self.folderPath}/MoreMore-{i}.png")
            self.scrollTo(500)
            sleep(1)
            self.driver.save_screenshot(f"{self.folderPath}/MoreMore-2-{i}.png")
            if i == 2:
                self.driver.save_screenshot(f"{self.folderPath}/AboutMoreMore.png")
                sleep(1)
                self.scrollTo(500)
                self.driver.save_screenshot(f"{self.folderPath}/AboutMoreMoreLink.png")
                for j in range(2,5):
                    btnOtherMore = self.driver.find_element(By.XPATH,f"//nav/div/div/div[{j}]/a")
                    btnOtherMore.click()
                    self.driver.save_screenshot(f"{self.folderPath}/AboutMoreMoreLink-{j}.png")
    #Bize Yazın
    def test_writeUs(self):
        btnWrite = self.driver.find_element(By.ID,"nexum_contactus_menu_label")
        btnWrite.click()
        sleep(1)
        self.driver.save_screenshot(f"{self.folderPath}/WriteUs.png")
        txtSearch = self.driver.find_element(By.ID,"contact_search_input")
        txtSearch.send_keys("Site Testi")
        self.driver.save_screenshot(f"{self.folderPath}/TXT.png")
        btnSearch = self.driver.find_element(By.XPATH,"//div/div/div/div/div/button")
        btnSearch.click()
        self.scrollTo(200)
        sleep(1)
        self.driver.save_screenshot(f"{self.folderPath}/SearchResult.png")
        btnDetail = self.driver.find_element(By.XPATH,"//div[3]/div[2]/div/a/span")
        btnDetail.click()
        sleep(2)
        for i in range(1,12):
            self.scrollTo(200)
            self.wait((By.XPATH,f"//div/div/div/div[2]/div/ul/li[{i}]/a"))
            btnDamageBag = self.driver.find_element(By.XPATH,f"//div/div/div/div[2]/div/ul/li[{i}]/a")
            btnDamageBag.click()
            sleep(1)
            self.driver.save_screenshot(f"{self.folderPath}/btnDamage-{i}.png")
            if i >= 7:
                self.scrollTo(500)

    #Diğer butonu
    def test_other(self):
        for i in range(1,24):
            self.wait((By.ID,"nexum_other_menu_label"))
            btnOther = self.driver.find_element(By.ID,"nexum_other_menu_label")
            self.action(btnOther)
            btnOtherUser = self.driver.find_element(By.ID,f"other_user_information_{i}_label")
            self.wait((By.ID,f"other_user_information_{i}_label"))
            btnOtherUser.click()
            self.scrollTo(200)
            sleep(1)
            self.driver.save_screenshot(f"{self.folderPath}/Others-{i}.png")
            if i == 23:               
                for j in range(2,9):
                    self.wait((By.ID,"nexum_other_menu_label"))
                    btnOther = self.driver.find_element(By.ID,"nexum_other_menu_label")
                    self.action(btnOther)
                    self.wait((By.ID,"other_destination_category"))
                    btnDestination = self.driver.find_element(By.ID,"other_destination_category")
                    btnDestination.click()
                    self.wait((By.XPATH,f"//li[6]/div/div/ul/li[2]/ul/li/ul/li[{j}]/a"))
                    btnTurkiye = self.driver.find_element(By.XPATH,f"//li[6]/div/div/ul/li[2]/ul/li/ul/li[{j}]/a")
                    btnTurkiye.click()
                    self.scrollTo(200)
                    sleep(1)
                    self.driver.save_screenshot(f"{self.folderPath}/Turkiye-{j}.png")
                for k in range(2,10):
                    self.wait((By.ID,"nexum_other_menu_label"))
                    btnOther = self.driver.find_element(By.ID,"nexum_other_menu_label")
                    self.action(btnOther)
                    self.wait((By.ID,"other_destination_category"))
                    btnDestination = self.driver.find_element(By.ID,"other_destination_category")
                    btnDestination.click()
                    self.wait((By.XPATH,f"//li[2]/ul/li[2]/ul/li[{k}]/a"))
                    btnTurkiye = self.driver.find_element(By.XPATH,f"//li[2]/ul/li[2]/ul/li[{k}]/a")
                    btnTurkiye.click()
                    self.scrollTo(200)
                    sleep(1)
                    self.driver.save_screenshot(f"{self.folderPath}/YurtDisi-{k}.png")
                if k == 9:
                    for l in range(1,4):
                        btnOther = self.driver.find_element(By.ID,"nexum_other_menu_label")
                        self.action(btnOther)
                        self.wait((By.ID,"other_human_resources_category"))
                        btnHumanResource = self.driver.find_element(By.ID,"other_human_resources_category")
                        btnHumanResource.click()
                        sleep(1)
                        self.driver.save_screenshot(f"{self.folderPath}/HumanBtn.png")
                        self.wait((By.ID,f"other_human_resources_{l}_label"))
                        btnHumanResources = self.driver.find_element(By.ID,f"other_human_resources_{l}_label")
                        btnHumanResources.click()
                        self.scrollTo(200)
                        sleep(1)
                        self.driver.save_screenshot(f"{self.folderPath}/HumanResources-{l}.png")
                    if l == 3:
                        btnOther = self.driver.find_element(By.ID,"nexum_other_menu_label")
                        self.action(btnOther)
                        self.wait((By.ID,"other_careers_main_ceategory"))
                        btnCarrier = self.driver.find_element(By.ID,"other_careers_main_ceategory")
                        btnCarrier.click()
                        sleep(1)
                        self.driver.save_screenshot(f"{self.folderPath}/CarrierBtn.png")
                        btnCarriers = self.driver.find_element(By.XPATH,"//li[4]/ul/li/ul/li/a")
                        btnCarriers.click()
                        self.scrollTo(100)
                        sleep(1)
                        self.driver.save_screenshot(f"{self.folderPath}/Carrier.png")
    #Arama butonu  testi                
    def test_search(self):
        txtSearch = self.driver.find_element(By.ID,"header-search-input")
        txtSearch.click()
        txtSearch.send_keys("uçuşlar")
        self.driver.save_screenshot(f"{self.folderPath}/SearchBtn.png")
        txtSearch.send_keys(Keys.ENTER)
        self.scrollTo(300)
        self.wait((By.XPATH,"//a[3]/span"))
        sleep(1)
        self.driver.save_screenshot(f"{self.folderPath}/SearchResult.png")
        btnDetails = self.driver.find_element(By.XPATH,"//a[3]/span")
        btnDetails.click()
        self.scrollTo(200)
        sleep(1)
        self.driver.save_screenshot(f"{self.folderPath}/SearchDetails.png")
    
    #Bilet alma testi
    def test_buyTicket(self):
        self.scrollTo(200)
        btnFromWhere = self.driver.find_element(By.XPATH,"//div[4]/div/div/div/div/div/div")
        btnFromWhere.click()
        txtFromWhere = self.driver.find_element(By.ID,"deperture-input")
        txtFromWhere.send_keys("Gaziantep")
        sleep(1)
        btnFromWhereClick = self.driver.find_element(By.XPATH,"//li/div/div[2]")
        btnFromWhereClick.click()
        sleep(1)
        self.driver.save_screenshot(f"{self.folderPath}/FromWhere.png")
        txtToWhere = self.driver.find_element(By.ID,"arrival-input")
        txtToWhere.send_keys("İstanbul")
        sleep(1)
        btnToWhere = self.driver.find_element(By.XPATH,"//div[3]/div[2]/div[3]/div[3]/ul/li/div/div")
        btnToWhere.click()
        sleep(1)
        self.driver.save_screenshot(f"{self.folderPath}/ToWhere.png")
        self.scrollTo(300)
        self.wait((By.XPATH,"//tr[6]/td/a"))
        btnGoingDate = self.driver.find_element(By.XPATH,"//tr[6]/td/a")
        btnGoingDate.click()
        self.wait((By.XPATH,"//div[2]/div[2]/div[5]/div[2]/div/a"))
        btnNextMonth = self.driver.find_element(By.XPATH,"//div[2]/div[2]/div[5]/div[2]/div/a")
        btnNextMonth.click()
        self.wait((By.XPATH,"//div[2]/div[2]/div[5]/div[2]/table/tbody/tr/td[5]/a"))
        btnBackDate = self.driver.find_element(By.XPATH,"//div[2]/div[2]/div[5]/div[2]/table/tbody/tr/td[5]/a")
        btnBackDate.click()
        self.wait((By.XPATH,"//div[6]/div/div/span"))
        btnParentsCount = self.driver.find_element(By.XPATH,"//div[6]/div/div/span")
        btnParentsCount.click()
        self.wait((By.XPATH,"//li/div/input"))
        txtPlus = self.driver.find_element(By.XPATH,"//li/div/input")
        txtPlus.send_keys(Keys.BACKSPACE)
        txtPlus.send_keys("2")
        self.wait((By.XPATH,"//div[6]/div/div[2]/a"))
        btnCount = self.driver.find_element(By.XPATH,"//div[6]/div/div[2]/a")
        btnCount.click()
        self.wait((By.ID,"search_cheap_flight_thirty_day_view_checkmark"))
        chk30Days = self.driver.find_element(By.ID,"search_cheap_flight_thirty_day_view_checkmark")
        chk30Days.click()
        self.driver.save_screenshot(f"{self.folderPath}/TicketSearch.png")
        btnSearch = self.driver.find_element(By.ID,"hype-search_cheap_flight_search_button")
        btnSearch.click()
        self.wait((By.XPATH,"//*[@id='boarding-card-body']/div/div[3]/div[1]/div[2]/div[2]/div[1]/div/div/div/div[6]"))
        btnOctober = self.driver.find_element(By.XPATH,"//*[@id='boarding-card-body']/div/div[3]/div[1]/div[2]/div[2]/div[1]/div/div/div/div[6]")
        btnOctober.click()
        self.scrollTo(600)
        self.wait((By.XPATH,"//*[@id='boarding-card-body']/div/div[3]/div[1]/div[2]/div[2]/div[3]/div[1]/div/div/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[6]/td[1]"))
        btnChooseDate = self.driver.find_element(By.XPATH,"//*[@id='boarding-card-body']/div/div[3]/div[1]/div[2]/div[2]/div[3]/div[1]/div/div/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[6]/td[1]")
        btnChooseDate.click()
        sleep(1)
        self.driver.save_screenshot(f"{self.folderPath}/TicketDates.png")
        self.scrollTo(1000)
        self.wait((By.XPATH,"//*[@id='boarding-card-body']/div/div[3]/div[3]/div/div[2]/button"))
        btnListOfTicket = self.driver.find_element(By.XPATH,"//*[@id='boarding-card-body']/div/div[3]/div[3]/div/div[2]/button")
        btnListOfTicket.click()
        sleep(10)

        